version: '3.9'
services:
  postgres:
    container_name: tachisync-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=tachisync
      - POSTGRES_PASSWORD=tachisync
    ports:
      - '5434:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local